backbone:
  config: mit_b1
  stride: [4, 2, 2, 1]
  comments: None

scheme: transwcd_single #transwcd_single, transwcd_dual

dataset:
  root_dir: /data/Dataset/Change Detection/WHU-CD-256
  name_list_dir: datasets/WHU
  num_classes: 2
  crop_size: 256
  rescale_range: [1.0, 1.0]   # [0.5, 2.0]不如[1.0, 1.0]


work_dir:
  dir: work_dir_WHU
  ckpt_dir: checkpoints
  pred_dir: predictions
  logger_dir: logger

train:
  split: train
  batch_size: 32  #
  max_iters: 8000
  cam_iters: 400   # 200, 400     # 2000, 5000，初始单独的iters，该cam_iters开始加入pixel pred
  eval_iters: 200
  log_iters: 200

cam:
  bkg_score: 0.45
  scales: [1, 0.5, 1.5, 2.0]   #[1, 0.5, 1.5]

val:
  split: val
  batch_size: 1

test:
  split: test
  batch_size: 1


optimizer:
  type: AdamW
  learning_rate: 6e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 1500
  warmup_ratio: 1e-6
  power: 1.0

mic:
  highpass_score: 0.6
  lowpass_score: 0.3